### ISSUE TITLE
Get working on Windows..

### ISSUE THREAD

**Issue by f0xforce** [axi0mX/ipwndfu#102]
:/ Release after added all supported devices

**Comment by DaJakerBoss** [comment]
This isn't really an issue, so why you opened this is beyond me since like _everyone_ is already talking about this

however, since you're here, why not try screwing around with WSL? I haven't heard anything about it working or not but according to Microsoft, WSL has full USB access, so there's a slight chance you could just open up a WSL install of Ubuntu, install `python` and `libusb-dev` and go from there.

Or even better, you could just make an Ubuntu LiveUSB and boot to that. I've done it, it works, and you don't actually have to install Ubuntu

### **PSA:** If you're a Windows user, you have no excuse not to use literally _any_ Linux LiveUSB to run this exploit, since it doesn't require you to install to your disk at all!

It's not that hard to make a LiveUSB, there's plenty of Linux distros that support this feature so you have plenty of choices, all you need is like a 4GB USB stick and there's a 99% chance your computer can boot to the stick. Bonus, once you're done with it, _nothing is left behind on the PC_. It's completely safe.

**Comment by f0xforce** [comment]
Not WSL pure Windows... so not need a VMs

**Comment by EWouters** [comment]
Please check #67 and close this issue.

**Comment by teamHFP** [comment]
Unsubscribe

**Comment by DaJakerBoss** [comment]
Regardless, and once again, this is still **not an issue**. Please close this OP, It will be around soon enough.

**Comment by adelphiamalloc** [comment]
you need an apple style compiler from what i understand.. no windowz
