### ISSUE TITLE
Keep getting error iphone 7 

### ISSUE THREAD

**Issue by Accountplugz** [axi0mX/ipwndfu#122]
Found: CPID:8010 CPRV:11 CPFM:03 SCEP:01 BDID:08 ECID:001C7916380BC326 IBFL:3C SRTG:[iBoot-2696.0.0.1.33]
Traceback (most recent call last):
  File "./ipwndfu", line 73, in <module>
    checkm8.exploit()
  File "/home/ubuntu/Desktop/ipwndfu-master/checkm8.py", line 510, in exploit
    if 'PWND:[checkm8]' not in device.serial_number:
  File "/home/ubuntu/Desktop/ipwndfu-master/usb/core.py", line 830, in serial_number
    self._serial_number = util.get_string(self, self.iSerialNumber)
  File "/home/ubuntu/Desktop/ipwndfu-master/usb/util.py", line 314, in get_string
    raise ValueError("The device has no langid")
ValueError: The device has no langid

now im getting this Found: CPID:8010 CPRV:11 CPFM:03 SCEP:01 BDID:08 ECID:001C7916380BC326 IBFL:3C SRTG:[iBoot-2696.0.0.1.33] PWND:[checkm8]
Device is already in pwned DFU Mode. Not executing exploit.

**Comment by EWouters** [comment]
The exploit is unreliable, it can take some tries to get it to work, hence your first error. After some tries it worked, hence the second message, This is the expected behavior. Verbose boot is only supported on the iPhone X. Use the `--boot` option to repair the heap and continue to normal boot.

Please close this issue.
