### ISSUE TITLE
Translate to Thunderbolt DFU to support T2 security chips

### ISSUE THREAD

**Issue by rickmark** [axi0mX/ipwndfu#141]
The T2 processor is almost identical in DFU protocol to USB DFU, but instead uses Thunderbolt as the transport.  Because of this sending the same payloads over Thunderbolt DFU will likely allow it to be used with the T2 chip as well.

**Comment by rickmark** [comment]
Sorry to top-post, but I did a bit of digging myself.

Turns out a T2 based MacBook will indeed work with only a USB controller to enter DFU mode (it seems the thunderbolt protocol is used at a later stage of restore).

For those interested, the reported DFU string states CPID:8012 - iBoot-3401.0.0.1.16

I think this is about enough to show that Checkm8 *MAY* work, but this is newer SecureROM; so that is assuming the USB heap issue wasn't patched in a later release.  But at the same time the chip used is about an A10, which means it will not have ARM pointer authentication codes, making it more likely to be quick work then the XS and future...

**Comment by baconwaifu** [comment]
Try adding a config entry with some preexisting offsets, it should at the very least crash the target, which should confirm vulnerability to the exploit. It's a bit more work after that to twist it into actual code execution though.

**Comment by MCMrARM** [comment]
When booting my T2-powered MBP2018 to DFU: `SerialNumber: CPID:8012 CPRV:10 CPFM:03 SCEP:01 BDID:0C ECID:#removed# IBFL:3C SRTG:[iBoot-3401.0.0.1.16]`
I tried adding a configuration identical to the 8011 or 8015 CPU, both quite obviously failed, but the chip rebooted from from DFU and showed as a rather weird device:
```
[ 7535.287769] usb 1-3: New USB device found, idVendor=05ac, idProduct=8600, bcdDevice= 2.01
[ 7535.287775] usb 1-3: New USB device strings: Mfr=1, Product=2, SerialNumber=3
[ 7535.287778] usb 1-3: Product: Apple T2 Controller
[ 7535.287781] usb 1-3: Manufacturer: Apple Inc.
[ 7535.287784] usb 1-3: SerialNumber: 000000000000
```
The computer itself did not reboot, but it seems that the T2 chip did.

I presume this means it's vulnerable, but I have no idea how to progress from there as it seems the offsets required are not easily obtainable.

**Comment by rickmark** [comment]
Curious @MCMrARM -

While the T2 isn't generally required for operation after boot, it does still handle in band encryption of the NVMe memory.  If you have a file operation occurring as you trip the reboot, does your system indicate a pause in the block storage??  This may indicate that Apple has factored in some either resiliency for the T2 or that reboots for things like T2 upgrades are a occurrence which has been accounted for....

**Comment by MCMrARM** [comment]
If you panic the T2, the NVMe drive becomes immediately non-operational and the laptop reboots 10 seconds later.

**Comment by rickmark** [comment]
Damn watchdog X-D

**Comment by h0m3us3r** [comment]
Any new progress on T2 in the past 3 months?

**Comment by rickmark** [comment]
Has been working successfully from linux on the USB transport (thunderbolt may therefore unneeded).  This is generally how to do a T2 restore...

Maybe we ought add the following to the wiki for the T2?

Building the world: https://gist.githubusercontent.com/rickmark/9245ed3ef7f36d5a0421557f68c4681b/raw/5d0d4846ba98cf72f810cdf07b895131ef386075/gistfile1.txt

Cleaning the world:
https://gist.githubusercontent.com/rickmark/9245ed3ef7f36d5a0421557f68c4681b/raw/5d0d4846ba98cf72f810cdf07b895131ef386075/clean_t2_restore.sh

Doing a Restore:

Follow these instructions
1) https://support.apple.com/guide/apple-configurator-2/revive-firmware-in-mac-computers-apdebea5be51/mac
2) https://gist.githubusercontent.com/rickmark/9245ed3ef7f36d5a0421557f68c4681b/raw/5d0d4846ba98cf72f810cdf07b895131ef386075/perform_t2_restore.sh

Locking down a Pi before hand (yes validated on x86_64 and arm)
https://gist.githubusercontent.com/rickmark/9245ed3ef7f36d5a0421557f68c4681b/raw/5d0d4846ba98cf72f810cdf07b895131ef386075/lockdown_pi.sh

In addition, it's related but not that I have reverse engineered Apple's USB Target Disk Mode and am currently working on pushing a driver to support to linux staging.  Will update here when it's stable:

https://github.com/rickmark/apple_utdm

**Comment by h0m3us3r** [comment]
I apologize if I am misunderstanding something, but isn't that just a standard dfu restore procedure? I was mainly asking about pwndfu with checkm8, as both t8002 and the t8012 under question were confirmed to be doable by @axi0mX (in this tweet: https://twitter.com/axi0mX/status/1182915286858522624?s=20), but the payload seems to only exist for the t8002 unless I'm missing something...

**Comment by rickmark** [comment]
Oh shoot, I had *supposed* they were but hadn’t seen confirmation: given that his code is public I should be able to adapt it, but need an older T2 mac since it’s based on the iBoot secure rom version.  I think this is why original iMac Pro’s are so expensive second hand...

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by rickmark** [comment]
Also this means that the T2 has become a GID Oracle for all T8012 (even with newer SecureROM).  Since they share a group key and some are pwn-able

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by h0m3us3r** [comment]
I thought all t8012s have 3401.0.0.1.16 bootrom. Are there ones with a newer version?

My understanding was that nobody had dumped 3401.0.0.1.16 to extract the offsets for the payload (or got the offsets by some other means), not that the payload did not work/only worked on some t8012s.

**Comment by rickmark** [comment]
Will confirm if this is true after BSides ...

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by h0m3us3r** [comment]
Let me know if I can be of any use, as I have a 2019 macbook, but I need to figure out how to boot the damned thing into dfu first. The apple-provided key-combo boots mine into internet recovery for some absurd reason...

**Comment by MCMrARM** [comment]
pretty sure the iMac Pro also has 3401.0.0.1.16: https://twitter.com/axi0mx/status/958054470537043968

**Comment by h0m3us3r** [comment]
Finally managed to boot my MBP2019 into DFU, and I can confirm that it still has `CPID:8012 CPRV:10 CPFM:03 SCEP:01 BDID:18 ECID:### IBFL:3C SRTG:[iBoot-3401.0.0.1.16]`

**Comment by rickmark** [comment]
Awesome!!! Now just need to find the offsets from a SecureROM dump, or brute force?!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by h0m3us3r** [comment]
The dump is not available anywhere I could think of looking. That only leaves guestimated bruteforce as far as I know.

**Comment by rickmark** [comment]
I’m sure it’s available somewhere, maybe someone with a copy floating around can let us know the offsets >.<

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by h0m3us3r** [comment]
Quick (and probably stupid) question: can the offsets be brute-forced one-by-one, or is there no way of verifying one without all others?

**Comment by h0m3us3r** [comment]
I can also confirm the behavior observed by @MCMrARM. Use of any configuration crashes t8012 straight out of dfu into the default "always-on" `Apple T2 Controller` mode (which is the mode the machine enumerates as when idle, and even when turned off).

**Comment by rickmark** [comment]
This is great news, means we have no HI for a brute

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by MCMrARM** [comment]
I considered doing a brute; I think it _might_ be doable. It's not obvious how to brute the offsets independently though, but what I thought of is something like the following:
First of all, jump into every possible address on a known vulnerable device which we have a dump of and do the same on the T2. This would let us find addresses that "don't crash" and probably should leak quite a bit of information about the code structure as well as limit down the amount of additional brute force needed (jumping into garbage will usually crash immediately due to stack misalignment and bad arguments; it only shouldn't crash when we're near a return). Then I'd try to look up and see if we can manage to find the subs in question already based on this info or not.

The main issue is that for this the T2 would need to be looped into DFU. There's a pinout on the motherboard that AFAIK could be used for this, but I don't want to lose Apple Care yet and I don't really have time to attempt it right now.

**Comment by h0m3us3r** [comment]
I thought of doing something similar, but I have a question. Why is the A11
(t8015) payload so drastically different from A10 (t8010, t8011)? Is it
because of architectiral changes of A10 -> A11, thus needing different
stuff to be done beforehand or is ot due to bootrom changes?(A10 achieves
code execution by first disabling wnx with a "disable_wnx" section that is
able to be run as memory is remapped in the call-chain. A11 does everything
from the call-chain, what exactly, I am not sure yet) Meaning, do you
expect the process for t8012 to be similar to t8010/t8011 or t8015? In
t8010's case we only need 4 pointers to get minimal code execution about
30% of the time; in t8015, we need way more. Also, comparing t8010 with
t8011, those 4 pointers are in a very close proximity, which could even
make manual brute possible if it's the same case for t8012. We can then use
that minimal code exec to dump rom through side channel.

I am totally willing to use hardware "FORCE_DFU" method for looping into
DFU myself, but unfortunately there is no schematic available for MBP2019,
and that is the only T2 machine that I have.

**Comment by h0m3us3r** [comment]
A simplest B 0 payload is confirmed to stall a vulnerable device forever without crashing. This payload needs minimum number of offsets (4 on t8010: nop_gadget, func_gadget, write_ttbr0, and tlbi) and can be used to validate code execution. I will try to jerry rig some brute forcing method later to find those 4 offsets for t8012.

All of the above is only valid if t8012 code injection procedure is same as for t8010/t8011.

**Comment by h0m3us3r** [comment]
After a bit more digging, it seems like we only need 2 offsets since nop_gadget is a part of func_gadget, and tlbi seems to be at a constant offset from write_ttbr0 across all versions.

**Comment by MCMrARM** [comment]
Try to look at the schematic for the 2018, it's very likely in a similar location because the Force DFU is actually a button.

**Comment by aunali1** [comment]
@h0m3us3r Its located here on the 13'inch models
<img width="609" alt="Screen Shot 2019-11-24 at 10 10 21 PM" src="https://user-images.githubusercontent.com/2416915/75389774-bdca6a80-58ac-11ea-8408-091a112d35f5.png">

**Comment by aunali1** [comment]
Here are also some more interesting debug interfaces/connectors that are left on the production board but not soldered. For the 15'inch models:
<img width="1016" alt="Screen Shot 2020-02-26 at 3 42 21 PM" src="https://user-images.githubusercontent.com/2416915/75390905-c459e180-58ae-11ea-8dff-e0d45e2c2a7a.png">

**Comment by rickmark** [comment]
To answer the questions of why the processors after T2 are so different, I’d guess both the bug got fixed, and that the introduction of ARM pointer authentication codes / KTRR (read only text regions) are the big causes...

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by h0m3us3r** [comment]
So far:
```
write_ttbr0 = None  # most likely within range: 0x1000003E4 ... 0x1000004AC (~~200~~ 50 possibilities)
tlbi = write_ttbr0 + 0x50

func_gadget = None  # most likely within range: 0x10000A404 ... 0x10000A9AC (362 possibilities)
nop_gadget = func_gadget + 0x18
```

Still can't come up with a method of brutting them one by one, and ~~72,400~~ 18,100 possible combinations is still too much.

**Comment by N00byEdge** [comment]
`0x1000003E4` to `0x1000004AC` is definitely 50. Still a little bit of a large space, so I would try to guess that they're really close to the t8010 offsets.

**Comment by h0m3us3r** [comment]
Yes, my bad. It's totally 50. The range is taken from t8015 and t8020 bootroms, based on bootrom version.

**Comment by h0m3us3r** [comment]
~~I think I have an idea that will let to brute them one by one. The idea is to modify call-chain to [(func_gadget, nop_gadget + 0x4)]. That will in theory lead to almost no crashes if func_gadget pointer is correct, and almost guaranteed crashes if it is not.~~

~~Finding write_ttbr0 after knowing func_gadget is trivial.~~

tried that, didn't work.

**Comment by h0m3us3r** [comment]
Ok, I brought the iteration time down to 1.5 seconds on average (on t8010). Bruting all likely pointers should only take about 8 hours. Just need to find the FORCE_DFU test point. (@aunali1, unfortunately, mpb2019 mlb is a complete redesign, and I couldn't find the needed tp based on those photos)

**Comment by rickmark** [comment]
This is incredible news...  (doh, read t8010 as t8012, the following refers to progress made on the T2 chip)

I have a MacMini I can use to confirm you're offsets / run a brute as well.

The consequences here are deep and profound:

- Exposure / reset of the Firmware password in SCfg
- Exposure of WPA-PSK stored in NVRAM
- Full control of the bridgeOS including early load EFI for the main processor (thereby affecting secure boot / internet recovery)
- Reset of FindMyMac
- Changing the serial of the device in SCfg?  (Unless it's in OTP memory??)
- Modifying both NVRAM of the x86 processor, as well as changing NVRAM for the T2, including debug flags (I've seen T2's with boot-args="debug=0x104c0c" be used)
- Modifying any byte on the NVMe disk

So this will clearly be a win for transparency, but also shows a capability that has been used for some time now by government / bad actors.

**Comment by rickmark** [comment]
![](https://images.macrumors.com/t/zpSU-Ro9xHl2xZDBjj9SiOo0weU=/2500x0/filters:no_upscale()/article-new/2018/11/mac-mini-teardown-3.jpg)

Hopefully someone knows the pins on that...

**Comment by h0m3us3r** [comment]
> Modifying any byte on the NVMe disk

I didn't really look into it much, but Isn't nvme read/write managed by sep?

**Comment by rickmark** [comment]
The T2 contains the SEP (and bootstraps it just like the iPhone does during boot), the AP makes PCIe requests for disk I/O to the T2, which then get passed to the backing store.  This is why disk is always bound to the T2 by way of the UID key

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by h0m3us3r** [comment]
Also,

> Changing the serial of the device in SCfg? (Unless it's in OTP memory??)

It is not in OTP on all iDevices (iPhone, iPad)

**Comment by h0m3us3r** [comment]
Found the test point. I think I might be blind... it is a button. In my defense, it is on the opposite side of the board from where T2 is.

**Comment by h0m3us3r** [comment]
Brute running. Unfortunately, it is up to 2.5 sec per iteration, so ~12 hours worst case. (Not considerimg an even worse case of ranges being wrong...)

**Comment by rickmark** [comment]
Care to share the brute code? Either public or DM so I can confirm on a different T2 model?


https://mobile.twitter.com/almightylinuxgo

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by h0m3us3r** [comment]
I dont mind sharing, but you'll need some hardware too, as T2 needs to be power cycled from time to time.

**Comment by rickmark** [comment]
I’ve got a 2019 Air and 2019 Mini, the Mini should be super easy to cycle (since it lacks battery)

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by h0m3us3r** [comment]
My brute is here https://github.com/h0m3us3r/ipwndfu

**Comment by rickmark** [comment]
Awesome, thanks for the contribution.  I’ll either port the code to a Pi or pick up an arduino this weekend

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by h0m3us3r** [comment]
Actually battery needs to be disconnected xD

T2 still boots into dfu with just usb power, and powercycling is done by splicing an arduino controlled rellay straight into usb cable...

**Comment by h0m3us3r** [comment]
Arduino code is trivial, it's just what I had lying on my desk. All it's doing is turning on the relay on 'P' from serial, and turning it off on 'p'. Initially it could control the force_dfu, but I deemed it useless and not using that feature.

Tbf, everything can be done from a pi, including brute itself, I was just too lazy to dig in the drawer for mine.

**Comment by aunali1** [comment]
@h0m3us3r Sorry, should have been clear about which side of the board that was. So to be clear, the T2 will stay in DFU mode as long as battery is not connected and USB power is supplied, irrespective of FORCE_DFU?

**Comment by h0m3us3r** [comment]
@aunali1 your photos are for different model (2018 vs 2019), and they did indeed help.

No, sorry, shoulve been more clear there, force_dfu still needs to be shorted to 1v8. I just ment that battery is not needed for dfu contrary to most (all) info I could find.

**Comment by rickmark** [comment]
Interesting, you’re saying the T2 is bus powered by the usb host (which means a hub where you can power on and off to reset)

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by h0m3us3r** [comment]
Bad news. Brute finished. Pointers not found :'(

Possible reasons:
1. Wrong offset range.
2. LOAD_ADDRESS needs to be different (but I don't seem to understand why is it different for t8010/t8011 vs t8015 to begin with and whether it is even important).
3. All of the above.
4. All of the above plus something else. Aka using t8010/t8011 procedure was wrong to begin with, and it needs to be done t8015/some other unknown way.
5. I am an idiot and fked something up in the code during transition t8010 -> t8012.

**Comment by h0m3us3r** [comment]
@rickmark 

> Interesting, you’re saying the T2 is bus powered by the usb host (which means a hub where you can power on and off to reset)

Yes, but if the battery is still plugged in, just cycling usb power will not reset T2. I am doing it with a usb cable, a relay spliced into the 5v line, and an arduino that controls said relay via serial. Keep in mind that FORCE_DFU still needs to be shorted to 1v8. On the plus side, there is absolutely no need to control FORCE_DFU; leaving it shorted to 1v8 at all times is perfectly fine (I was not sure about that, and it's the reason why my arduino code is made to control another relay that shorts FORCE_DFU).

**Comment by rickmark** [comment]
This makes some sense:  since the T2 ate the SMC which controls system power battery etc, and needs be programmed on a new board, it makes sense that it could operate on separate power...

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by h0m3us3r** [comment]
That is not a feature unique to T2 by the way. All Ax's are same too. Not sure about Sx's, but wouldn't be surprised if they do same too.

**Comment by aunali1** [comment]
@rickmark So for the 2019 MBA it requires some more modification to the MLB.
![image](https://user-images.githubusercontent.com/2416915/75599365-d3d15a00-5a69-11ea-8b49-873550916c85.png)
Rather than a button, it is a bog-standard test point. Also, based on these images, you'll need to solder a 2.2k Ohm 1/20W 5% SMD resistor on R8010 (in yellow).

**Comment by h0m3us3r** [comment]
@aunali1 I have 2019 Pro, not Air. But anyway, I found it yesterday already, it is a button. I was looking near T2, but it is across whole board, near battery connector. I already run a brute, and got no pointers...

Out of frustration, and due to the lack of further ideas, I'm setting another brute with about 130,000 combinations. Will give me a ~4 days break to think about some other way, because something tells me it will be nothing again.

**Comment by MCMrARM** [comment]
How do you check whether the brute gave meaningful results?

**Comment by MCMrARM** [comment]
also, tbh unfortunate that the iBoot on the t8012 is actually newer than t8015; otherwise we'd be able to do more meaningful assumptions.

edit: doesn't this basically make these likely ranges not really likely?
https://github.com/h0m3us3r/ipwndfu/commit/8c87ff9f4c2a4736e56819b9db13d1570e407f83#diff-24c8c2126a7bd4a92b45374fbf1a82e4R199

edit2: According to my memory layout exploitation tests, on the T2 the PCIe part of iBoot is disabled/removed. Therefore it might be possible that the function moved to an even lower address.

**Comment by h0m3us3r** [comment]
It is not newer than t8020, it is between t8015 and t8020 (closer to
t8015). Both roms are available.

**Comment by h0m3us3r** [comment]
Comparing t8015 an t8020 was how I got my 1st brute range. But I went with
the assumption that the procedure needed for t8015 is silicon related, and
used t8010 procedure, which might not be true.

**Comment by h0m3us3r** [comment]
@MCMrARM 

> How do you check whether the brute gave meaningful results?

If offsets are correct, we get code execution, and the cpu gets stuck in B 0 (branch to offset 0, or to itself, the 0x00000014 opcode). It will disconnect from host in the process and we wont be able to dfu.acquire_device()

If offsets are incorrect, T2 will crash, but since we have FORCE_DFU asserted, it will boot straight into dfu, and we will be able to dfu.acquire_device(). We can try next combination immediately if this is the case.

There is another possible outcome, but it happens quite rarely: the exploit didn't work. In this case, T2 does not crash, nor gets stuck. We can dfu.acquire_device(), but it takes much less time than if T2 crashed (1 ms vs ~900 ms for T2). If we get this outcome, we have to reset the T2 before we try the next combination of offsets.

**Comment by h0m3us3r** [comment]
@MCMrARM 

> doesn't this basically make these likely ranges not really likely?

Why would that be?

**Comment by MCMrARM** [comment]
I wonder if the ~~t8012~~t8020 has the PCI subsystem enabled in SecureROM.

Well, I messed up with the t8020/t8015 thing, so I guess you're right, it makes sense. If indeed t8015 had bootrom older than t8012 then the offset range would be most likely completely different.

edit: meant t8020, not t8012 so corrected that, I am pretty sure that t8012 has it disabled.

**Comment by h0m3us3r** [comment]
~~Not sure how I missed it the first time, but I am a dummy, took a look at my 1st range, and the result is just slightly out of it. Anyway, my second run found
`func_gadget: 0x10000ad14	write_ttbr0: 0x1000004a4`
as a possible combination.~~

~~This still does not give us pwndfu, as we don't know a big lot of other pointers, but (if those two are correct, further testing needed), we do have code execution now, and can do memory search for the missing ones. My asm-fu is not strong enough for that though.~~

False alert, pointers are wrong.

**Comment by h0m3us3r** [comment]
Actually, we are only missing `USB_CORE_DO_IO` and `usb_create_string_descriptor`

**Comment by MCMrARM** [comment]
If we do achieve code exec, I should be able to do shellcode for finding the remaining ones.

**Comment by MCMrARM** [comment]
@h0m3us3r I mean I can't 100% guarantee it wasn't already disabled on the t8010 (I think I checked it and it wasn't disabled there but honestly this was like half a year ago) but the t8012 disabled the PCI subsystem and wouldn't this break the heap spray?

I remember trying to figure out the proper offset for heap spraying but never managed to match it up with ipwndfu's for some reason. (I can share my code; it's a C project that does allocations in the same order as iBoot and of the same size; based on the allocator from the leaked iBoot source code). It was always off by 0x40, and I have no idea what did I do wrong.

edit: might be unclear; never managed to match it up on t8010.

edit2: the reason why I mention the removal of the PCI subsystem is because it removes the pci bridge allocation (it is a 0x200 structure), so this can definitely affect things, just not sure if at this point or not.

edit3: not sure how useful this broken code is but according to it the missing allocation shouldn't change anything but i mean, that can be just as well wrong because it's off by 0x40.

**Comment by h0m3us3r** [comment]
@MCMrARM, @rickmark 
I suggest moving this conversation off of this issue thread and to slack/discord. PM me at h0m3us3r@warranty-void.com for an invite if you agree.

**Comment by h0m3us3r** [comment]
Quick question: what determines load_address?

@MCMrARM, I sent you the invite btw, did you get it?

**Comment by rickmark** [comment]
#226 resolves this issue

**Comment by rickmark** [comment]
I feel like we can close this issue as resolved,

As I understand PRs are not being accepted

**Comment by sasimaci** [comment]
Found: CPID:8012 CPRV:10 CPFM:03 SCEP:01 BDID:18 ECID:000D253202230026 IBFL:3C SRTG:[iBoot-3401.0.0.1.16]
ERROR: This device is not supported.
mac@macs-MacBook-Pro ipwndfu % 
any help !!

**Comment by h0m3us3r** [comment]
Use my or @MCMrARM fork.

**Comment by jbwaring** [comment]
@aunali1 
Dear Aunali1, could you share your sources for the board pictures with t2 force dfu pads? I am trying to get an A2141 to dfu without the internal keyboard.
