### ISSUE TITLE
Iphone X 0xFFF does not fix this

### ISSUE THREAD

**Issue by DarkNetHeros** [axi0mX/ipwndfu#162]
*** checkm8 exploit by axi0mX ***
Found: CPID:8015 CPRV:11 CPFM:03 SCEP:01 BDID:06 ECID:000A18D40438E02E IBFL:3C SRTG:[iBoot-3332.0.0.1.23]
Traceback (most recent call last):
  File "/Users/evans/Desktop/123/ipwndfu", line 77, in <module>
    checkm8.exploit()
  File "/Users/evans/Desktop/123/checkm8.py", line 472, in exploit
    payload, config = exploit_config(device.serial_number)
  File "/Users/evans/Desktop/123/checkm8.py", line 454, in exploit_config
    return payload(config.cpid), config
  File "/Users/evans/Desktop/123/checkm8.py", line 419, in payload
    t8015_handler = asm_arm64_x7_trampoline(t8015_handle_interface_request) + asm_arm64_branch(0x10, 0x0) + prepare_shellcode('usb_0xA1_2_arm64', constants_usb_t8015)[4:]
  File "/Users/evans/Desktop/123/checkm8.py", line 106, in prepare_shellcode
    with open('bin/%s.bin' % name, 'rb') as f:
IOError: [Errno 2] No such file or directory: 'bin/usb_0xA1_2_arm64.bin'

**Comment by DarkNetHeros** [comment]
edited the checkm8.py and now im getting this error


Evanss-iMac:~ evans$ /Users/evans/Desktop/123/ipwndfu -p
Traceback (most recent call last):
  File "/Users/evans/Desktop/123/ipwndfu", line 7, in <module>
    import alloc8, checkm8, image3_24Kpwn, limera1n, SHAtter, steaks4uce, usbexec
  File "/Users/evans/Desktop/123/checkm8.py", line 482
    usb_req_leak(device)
               ^
IndentationError: expected an indented block
Evanss-iMac:~ evans$ /Users/evans/Desktop/123/ipwndfu -p
Traceback (most recent call last):
  File "/Users/evans/Desktop/123/ipwndfu", line 7, in <module>
    import alloc8, checkm8, image3_24Kpwn, limera1n, SHAtter, steaks4uce, usbexec
  File "/Users/evans/Desktop/123/checkm8.py", line 482
    usb_req_leak(device)
               ^
IndentationError: expected an indented block

**Comment by meowox** [comment]
You don't know what you're doing. Don't use this. 
1) This doesn't support Windows
2) You don't have the usb_0xA1_2_arm64.bin in your bin folder. I don't know what you've done to "edit" the checkm8.py but that would not work.
3) You're not on the latest version of ipwndfu.
4) Python very intuitively told you it's expecting an indented block. If you had to open an issue for this, you probably should keep away from messing with it. Or at least don't create issues about these non-issues.

**Comment by Valentinez** [comment]
This is not a Bug in the Code.

First Post:
Error Message States you are missing a file,
Specifically: `bin/usb_0xA1_2_arm64.bin`

This is because you Ran the code from Home, 
and decided to include the whole path to ipwndfu, to run it.

The 2nd error is because you are messing with code, 
and don't know how to format it.

Error Code LITERATELY tells you what to do.
- Indent the Line...

So first, undo what you did to Checkm8.py,

**_Looks like you're using a Mac_**
I don't use Mac, but I can give the comparable Linux Commands.

[Linux Commands]
Then, in a Terminal: 
`cd /Users/evans/Desktop/123`

Then Run:
`sudo ./ipwndfu -p`
-or-
`sudo python ipwndfu -p`
_If you have Python3, you may need to get Python 2.7_
And Run:
`sudo python2.7 ipwndfu -p`

Because when you Run:
`/Users/evans/Desktop/123/ipwndfu -p`

It's trying to look for the file dependencies in `/home/evans/`
_and they are not there_
It's because that's where you are running the Command from.

This isn't an Error in the Code, it's an Error in your understanding of how to use it.

Please Close the Issue?

**Comment by ps4gentoo** [comment]
any Fork for Iphone X with iOS12.4? 
verbose boot doesnt work ..  kernel panic?

tested this https://github.com/Davidescion/ra1nbowsn0w/ 
with command --bypass124 but doesnt work ..


```
python2.7 ipwndfu -p --bypass124
*** checkm8 exploit by axi0mX ***
Found: CPID:8015 CPRV:11 CPFM:03 SCEP:01 BDID:0E ECID:000XXXXXXXXXXXX IBFL:3C SRTG:[iBoot-3332.0.0.1.23] PWND:[checkm8]
Device is already in pwned DFU Mode. Not executing exploit.
```

verbose-boot doesnt work ;/ 


this Fork work for iPhone X iOS 12.4
https://github.com/FatMeowXD/ipwndfu

**Comment by Valentinez** [comment]
Well yeah, because Verbose Booting is only for iOS 13 for now...
so I've read... 
you know... 
in the README...
