### ISSUE TITLE
Exploit not installing

### ISSUE THREAD

**Issue by brsgaming804** [axi0mX/ipwndfu#26]
Output message:

`sudo ./ipwndfu -x

Installing alloc8 exploit to NOR.
Dumping NOR, part 1/8.
Dumping NOR, part 2/8.
Dumping NOR, part 3/8.
Dumping NOR, part 4/8.
Dumping NOR, part 5/8.
Dumping NOR, part 6/8.
libusb 0.000000 info [event_thread_main] thread exiting
Dumping NOR, part 7/8.
Dumping NOR, part 8/8.
NOR backed up to file: nor-backups/not-0000005786136D0E-20170621-200016.dump
libusb 22.550642 info [event_thread_main] thread exiting
Sending iBSS.`

I already installed the custom firmware (3.1.3) made with PwnageTool and that was successful. But, I'm still stuck in DFU.

**Comment by axi0mX** [comment]
What version of macOS? What year/model Mac?

Is there no further output after ```Sending iBSS.```?

This is unusual:
```libusb 22.550642 info [event_thread_main] thread exiting```

**Comment by brsgaming804** [comment]
No further output. It's a Macbook 2,1 and has OSX 10.7.5 because I don't have any other computers that can run Linux/

**Comment by axi0mX** [comment]
I don't know why, it is a very old version of OS X. People reported success on Mavericks, perhaps Mountain Lion would work too. 

Though not supported officially, you should be able to install El Capitan on your MacBook. Graphics acceleration might not work, not sure if that was solved since this thread started:
https://forums.macrumors.com/threads/os-x-el-capitan-on-unsupported-macs.1889851/

Though not supported officially, Mountain Lion should work too, with graphics acceleration:
https://forums.macrumors.com/threads/guide-success-install-10-8-on-old-unsupported-mac.1325709/

If you don't want to install a newer version of OS X, try Ubuntu. I tested ipwndfu on Ubuntu and it worked.

**Comment by brsgaming804** [comment]
I tried it on Ubuntu, ran it with sudo, and it worked!

**Comment by axi0mX** [comment]
Thanks for the report.
