### ISSUE TITLE
Error 28

### ISSUE THREAD

**Issue by NicklasWabra** [axi0mX/ipwndfu#7]
When I try to restore, I get error 28:(

**Comment by axi0mX** [comment]
1. Is your iPhone 3GS manufactured on or after Week 28, 2011? You can find this in the serial number.
2. Are you flashing iOS 3.x?

**Comment by NicklasWabra** [comment]
I think it's made after 

And yes I am

**Comment by NicklasWabra** [comment]
It was made In week 36

**Comment by axi0mX** [comment]
Based on your report and reports from others, it seems that iPhone 3GS devices made after Week 28 2011 might be incompatible with iOS 3.x, because the baseband is different.

For now, there is no known way to restore 3.x. You should be able to restore 4.0, 4.3.3, 5.0.1, 5.1, 5.1.1 by following the guide.

I'll add this information there.

**Comment by axi0mX** [comment]
Let me know if 4.0 or above works for you.

**Comment by NicklasWabra** [comment]
It works with 4.0

**Comment by axi0mX** [comment]
Thank you for the report. Thus far I have the following reports about HW compatibility with older versions:

Week 23 2011 (3.x worked)
Week 29 2011 (3.x did not work, 4.0 worked)
Week 36 2011 (3.x did not work, 4.0 worked)
Week 26 2012 (4.3.3 did not work, 5.0 worked)

I'll need to look into this more.

**Comment by NicklasWabra** [comment]
Alright. Send me a message on twitter @NicklasWabra, if you need anything:)

**Comment by axi0mX** [comment]
Cool. Thanks for the update. Great to hear it worked with 4.0.
